apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: crop-advisor
type: Opaque
stringData:
  django-secret-key: "REPLACE_WITH_DJANGO_SECRET_KEY"
  db-password: "REPLACE_WITH_DB_PASSWORD"
  brevo-api-key: "REPLACE_WITH_BREVO_API_KEY"
  brevo-sender-email: "REPLACE_WITH_BREVO_SENDER_EMAIL"
  brevo-sender-name: "REPLACE_WITH_BREVO_SENDER_NAME"
  celery-broker-url: "REPLACE_WITH_CELERY_BROKER_URL"
  celery-result-backend: "REPLACE_WITH_CELERY_RESULT_BACKEND"
