apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: crop-advisor
type: Opaque
stringData:
  BREVO_API_KEY: "REPLACE_WITH_BREVO_API_KEY"
  BREVO_SENDER_EMAIL: "REPLACE_WITH_BREVO_SENDER_EMAIL"
  BREVO_SENDER_NAME: "REPLACE_WITH_BREVO_SENDER_NAME"
  CELERY_BROKER_URL: "REPLACE_WITH_CELERY_BROKER_URL"
  CELERY_RESULT_BACKEND: "REPLACE_WITH_CELERY_RESULT_BACKEND"
  DB_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  DJANGO_SECRET_KEY: "REPLACE_WITH_DJANGO_SECRET_KEY"
  DJANGO_SUPERUSER_EMAIL: "REPLACE_WITH_DJANGO_SUPERUSER_EMAIL"
  DJANGO_SUPERUSER_PASSWORD: "REPLACE_WITH_DJANGO_SUPERUSER_PASSWORD"
  GEMINI_API_KEY: "REPLACE_WITH_GEMINI_API_KEY"
