grafana:
  adminPassword: "CropAdvisor@123"
  service:
    type: NodePort
    nodePort: 30300

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 15s
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
    additionalScrapeConfigs:
      - job_name: crop-advisor-backend
        metrics_path: /metrics
        static_configs:
          - targets:
              - backend-svc.crop-advisor.svc.cluster.local:8000

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
