apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: crop-advisor
data:
  ACCESS_TOKEN_LIFETIME_MINUTES: "120"
  ALLOWED_HOSTS: "75.101.134.224,52.70.118.130,44.194.224.52,localhost,127.0.0.1,backend-svc,backend-svc.crop-advisor.svc.cluster.local"
  AUTH_HEADER_TYPES: "Bearer"
  BLACKLIST_AFTER_ROTATION: "True"
  CSRF_TRUSTED_ORIGINS: "http://75.101.134.224:30080,http://52.70.118.130:30080,http://44.194.224.52:30080,http://localhost:3000,http://127.0.0.1:3000"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_HOST: "aws-1-ap-southeast-1.pooler.supabase.com"
  DB_NAME: "postgres"
  DB_PORT: "5432"
  DB_SSLMODE: "require"
  DB_USER: "postgres.qtabdrszliiqqykdqmek"
  DJANGO_SETTINGS_MODULE: "core.settings"
  DEBUG: "False"
  REFRESH_TOKEN_LIFETIME_DAYS: "7"
  ROTATE_REFRESH_TOKENS: "False"
  UPDATE_LAST_LOGIN: "True"
